language: python
cache: pip

sudo: false

python:
  - "3.6"

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
